In [1]:
from pandas import Series, DataFrame
import numpy as np

In [3]:
s1 = Series([1,2,3,4],index=['a','b','c','d'])
print(s1)

a    1
b    2
c    3
d    4
dtype: int64


In [4]:
s2 = Series([5,6,7,8],index=['a','b','c','d'])
print(s2)

a    5
b    6
c    7
d    8
dtype: int64


In [5]:
# 인덱스의 이름이 동일하면 연산가능
print(s1+s2)

a     6
b     8
c    10
d    12
dtype: int64


In [12]:
# 9는 정수 9. 하면 실수 , # 리스트 쓰면 한글자씩 잘라서 사용
df1 = DataFrame(np.arange(9.).reshape(3,3),columns=list('abc'),index=['서울','도쿄','뉴욕']) 
df1

a    b    c
서울  0.0  1.0  2.0
도쿄  3.0  4.0  5.0
뉴욕  6.0  7.0  8.0

In [17]:
df2 = DataFrame(np.arange(12.).reshape(4,3),index=['서울','도쿄','뉴욕','북경'],columns=list('abc'))
df2

a     b     c
서울  0.0   1.0   2.0
도쿄  3.0   4.0   5.0
뉴욕  6.0   7.0   8.0
북경  9.0  10.0  11.0

In [18]:
print(df1+df2)

       a     b     c
뉴욕  12.0  14.0  16.0
도쿄   6.0   8.0  10.0
북경   NaN   NaN   NaN
서울   0.0   2.0   4.0


In [20]:
print(df1.add(df2,fill_value=0)) # NaN 은 0으로 대체 , 합칠때 없는 함수를 이용하기 위해

       a     b     c
뉴욕  12.0  14.0  16.0
도쿄   6.0   8.0  10.0
북경   9.0  10.0  11.0
서울   0.0   2.0   4.0


In [27]:
print("기술 통계량 제공 메서드 와 NaN처리")
df = DataFrame([[1.4,np.nan],[7,-4.5],[np.nan,np.nan],[0.5,-1]],columns=["one","two"],index=['a','b','c','d'])
df

기술 통계량 제공 메서드 와 NaN처리


one  two
a  1.4  NaN
b  7.0 -4.5
c  NaN  NaN
d  0.5 -1.0

In [28]:
print(df.dropna(how='all')) # 행(one,two 둘다) 전체가 NaN은 제거

   one  two
a  1.4  NaN
b  7.0 -4.5
d  0.5 -1.0


In [29]:
# na를 0으로 처리
print(df.fillna(0))

   one  two
a  1.4  0.0
b  7.0 -4.5
c  0.0  0.0
d  0.5 -1.0


In [30]:
print(df.sum(axis=0)) # x축 기준으로 열 합계

one    8.9
two   -5.5
dtype: float64


In [31]:
print(df.sum(axis=1)) # Y축 기준으로 열 합계

a    1.4
b    2.5
c    0.0
d   -0.5
dtype: float64


In [33]:
# 열 기준으로 평균을 구하기
print(df.mean(axis=1).fillna(0))

a    1.40
b    1.25
c    0.00
d   -0.25
dtype: float64


In [35]:
# Nan은 연산에서 제외
print(df.mean(axis=1,skipna=False))

a     NaN
b    1.25
c     NaN
d   -0.25
dtype: float64


In [36]:
df.count(axis=0)

one    3
two    2
dtype: int64

In [37]:
df.count(1) # 매개변수 어떤것이 첫번째로 오는지 안다면 생략하고 써도 된다

a    1
b    2
c    0
d    2
dtype: int64

In [39]:
df.std(0)

one    3.521837
two    2.474874
dtype: float64

In [40]:
df.quantile(0.25) # 사분위수

one    0.950
two   -3.625
Name: 0.25, dtype: float64

In [41]:
df.describe() # 통합해서 보기

one       two
count  3.000000  2.000000
mean   2.966667 -2.750000
std    3.521837  2.474874
min    0.500000 -4.500000
25%    0.950000 -3.625000
50%    1.400000 -2.750000
75%    4.200000 -1.875000
max    7.000000 -1.000000

In [43]:
word = Series(['봄','여름','봄','겨울','봄','여름','봄','가을','봄','여름','봄','여름','가을'])
word.describe()

count     13
unique     4
top        봄
freq       6
dtype: object

In [44]:
# pandas 를 사용한  I/O
import pandas as pd
# 자동완성안되면 임포트 먼저 실행후 다시 하면 된다
df = pd.read_csv('dept.csv') # csv는 파일자체가 ,로 구분되어 있는 파일
df

DEPTNO       DNAME       LOC
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [45]:
df2 = pd.read_table('dept.csv',sep=',') # read_table 은 sep 구분자를 지정해야 된다
df2

DEPTNO       DNAME       LOC
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [46]:
df3=pd.read_csv('dept.csv') # 컬럼헤딩이 없는 데이터라면  header = None
print(df3)

   DEPTNO       DNAME       LOC
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON


In [47]:
df4=pd.read_csv('dept.csv',names=['부서번호','부서명','위치']) # 컬럼 이름을 줄거라면
print(df4)

     부서번호         부서명        위치
0  DEPTNO       DNAME       LOC
1      10  ACCOUNTING  NEW YORK
2      20    RESEARCH    DALLAS
3      30       SALES   CHICAGO
4      40  OPERATIONS    BOSTON


In [49]:
# 컬럼 이름을 지정하고 컬럼헤딩 제거
print(df4[df4.index>=1])

  부서번호         부서명        위치
1   10  ACCOUNTING  NEW YORK
2   20    RESEARCH    DALLAS
3   30       SALES   CHICAGO
4   40  OPERATIONS    BOSTON


In [53]:
# student1.txt 파일 읽기 , 가끔 안읽어오면 파일 자체를 utf8로 다른이름으로 저장하면 된다
df5=pd.read_csv('student1.txt',sep="\t",encoding="utf-8") # 언어가 다를경우 인코딩도 가능
df5

번호    이름    키  몸무게
0  101  hong  175   65
1  201   lee  185   85
2  301   kim  173   60
3  401  park  180   70

In [54]:
# 1,3 라인 제거하고 가져오기 (필요없는 라인 제거)
df6=pd.read_csv('student1.txt',sep="\t",encoding="utf-8",skiprows=[1,3])
df6

번호    이름    키  몸무게
0  201   lee  185   85
1  401  park  180   70

In [55]:
print("저장하기")

저장하기


In [56]:
df.to_csv('test1.csv',sep=',') # 색인포함(index번호)

In [57]:
%ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 76CD-579A

 C:\Users\acorn\jupyter_workspace 디렉터리

2018-10-26  오전 10:51    <DIR>          .
2018-10-26  오전 10:51    <DIR>          ..
2018-10-26  오전 09:46    <DIR>          .ipynb_checkpoints
2018-10-25  오전 10:06           539,885 day1.ipynb
2018-10-25  오후 06:15           101,231 day2.ipynb
2018-10-26  오전 10:49            26,119 day3.ipynb
2018-10-26  오전 10:35               102 dept.csv
2018-10-25  오후 03:12    <DIR>          img
2018-10-24  오후 04:09               262 korea.txt
2018-10-23  오후 05:16               845 ML01.ipynb
2018-10-24  오후 03:46               525 populations.txt
2018-10-25  오후 12:12                66 student.txt
2018-10-26  오전 10:43                98 student1.txt
2018-10-25  오전 10:08               164 test.npy
2018-10-26  오전 10:51               111 test1.csv
2018-10-25  오후 12:28                 0 test2.txt
2018-10-23  오후 05:14                72 Untitled.ipynb
2018-10-24  오전 10:07                72 Untitled1.ipynb
2018-10-25  오전 09:31

In [58]:
df.to_csv('test2.csv',sep=',',index=False) # index 번호 없음

In [59]:
df.to_csv('test3.csv',sep=',',index=False, header=False) # \ header 없음

In [62]:
# student1.txt 파일을 읽어 dataframe객체 df를 생성
df=pd.read_csv('student1.txt',sep='\t')
df

번호    이름    키  몸무게
0  101  hong  175   65
1  201   lee  185   85
2  301   kim  173   60
3  401  park  180   70

In [83]:
# 키와 몸무게의 합계 , 평균
print("합계:\n",df.sum()[['키','몸무게']])
print("평균:\n",df.mean()[['키','몸무게']])

합계:
 키      713
몸무게    280
dtype: object
평균:
 키      178.25
몸무게     70.00
dtype: float64


In [86]:
print("--------JSON (JavaScript Object Notation)은 경량의 DATA-교환 형식 ----------")

--------JSON (JavaScript Object Notation)은 경량의 DATA-교환 형식 ----------


In [108]:
obj = """
{"name":"scott",
"language" :["C","C++","java","python","한국어"],
"age":20,
"exam":[{"first":80,"second":100},{"first":95,"second":70}]
}
"""
obj

'\n{"name":"scott",\n"language" :["C","C++","java","python","한국어"],\n"age":20,\n"exam":[{"first":80,"second":100},{"first":95,"second":70}]\n}\n'

<h3>obj는 현재 JSON 형식의 문자열이다

In [121]:
import json
import requests
import pandas as pd

In [110]:
result = json.loads(obj)
result

{'name': 'scott',
 'language': ['C', 'C++', 'java', 'python', '한국어'],
 'age': 20,
 'exam': [{'first': 80, 'second': 100}, {'first': 95, 'second': 70}]}

In [111]:
print(type(result))

<class 'dict'>


In [112]:
jsonObj = json.dumps(obj)
jsonObj

'"\\n{\\"name\\":\\"scott\\",\\n\\"language\\" :[\\"C\\",\\"C++\\",\\"java\\",\\"python\\",\\"\\ud55c\\uad6d\\uc5b4\\"],\\n\\"age\\":20,\\n\\"exam\\":[{\\"first\\":80,\\"second\\":100},{\\"first\\":95,\\"second\\":70}]\\n}\\n"'

In [113]:
print(type(jsonObj))

<class 'str'>


In [114]:
# result의 값중 name
result['name']

'scott'

In [116]:
# JSON 타입의 객체를 Series 객체로 만들어 낼 수 있다
jsonname = pd.Series(result['language'])
jsonname

0         C
1       C++
2      java
3    python
4       한국어
dtype: object

In [117]:
# Dataframe ?
df = DataFrame(result['language'])
df

0
0       C
1     C++
2    java
3  python
4     한국어

In [127]:
print("웹에 있는 json 읽기")
url ="http://192.168.0.206/bigdata/jsonTest.txt"
resp = requests.get(url)
data = resp.json()
print(data)
print(type(data))

웹에 있는 json 읽기
{'name': ['scott', 'smith'], 'age': [22, 30], 'job': ['manager', 'analyst']}
<class 'dict'>


In [130]:
# job 만 가져오기
print(data['job'])

['manager', 'analyst']


In [132]:
#data = {"test":"hong","age":20}
df = pd.DataFrame(data)
df

name  age      job
0  scott   22  manager
1  smith   30  analyst

In [133]:
# 0 scott 200 manager
df.iloc[0]

name      scott
age          22
job     manager
Name: 0, dtype: object

In [135]:
# 자료 합치기
from pandas import DataFrame,Series
import numpy as np
import pandas as pd

df1 = DataFrame({"key":['b','b','a','c','a','a','b'], "data1":range(7)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [136]:
df2 = DataFrame({"key":['a','b','d'], "data2":range(3)})
df2

key  data2
0   a      0
1   b      1
2   d      2

In [137]:
print("--------------------")
print(pd.merge(df1,df2, on = "key"))

--------------------
  key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0


In [138]:
print(pd.merge(df1,df2, on = "key",how="inner")) # 교집함

  key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0


In [139]:
print(pd.merge(df1,df2, on = "key",how="outer")) # 합집합

  key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0


In [140]:
print(pd.merge(df1,df2, on = "key",how="left")) 

  key  data1  data2
0   b      0    1.0
1   b      1    1.0
2   a      2    0.0
3   c      3    NaN
4   a      4    0.0
5   a      5    0.0
6   b      6    1.0


In [141]:
print(pd.merge(df1,df2, on = "key",how="right"))

  key  data1  data2
0   b    0.0      1
1   b    1.0      1
2   b    6.0      1
3   a    2.0      0
4   a    4.0      0
5   a    5.0      0
6   d    NaN      2


In [142]:
# 공통의 컬럼이 없을 경우
df3 = DataFrame({"key2":['a','b','c'],"data3":range(3)})
df3

key2  data3
0    a      0
1    b      1
2    c      2

In [143]:
pd.merge(df1,df3, left_on="key",right_on="key2")

key  data1 key2  data3
0   b      0    b      1
1   b      1    b      1
2   b      6    b      1
3   a      2    a      0
4   a      4    a      0
5   a      5    a      0
6   c      3    c      2

In [144]:
print("numpy 의 ndarray형 자료 합치기")

numpy 의 ndarray형 자료 합치기


In [146]:
arr1 = np.arange(6).reshape(2,3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [147]:
arr2 = np.arange(4,10).reshape(2,3)
arr2

array([[4, 5, 6],
       [7, 8, 9]])

In [148]:
arrs = np.concatenate([arr1,arr2],axis=0)
arrs

array([[0, 1, 2],
       [3, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
arrs = np.concatenate([arr1,arr2],axis=1)
arrs

array([[0, 1, 2, 4, 5, 6],
       [3, 4, 5, 7, 8, 9]])

In [150]:
s1= Series([0,1],index=['a','b'])

s2= Series([2,3,4], index=['c','d','e'])

s3= Series([5,6],index=['f','g'])

print(s1)

a    0
b    1
dtype: int64


In [151]:
print(s2)
print(s3)

c    2
d    3
e    4
dtype: int64
f    5
g    6
dtype: int64


In [153]:
print(pd.concat([s1,s2,s3],axis=0))

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64


In [155]:
print(pd.concat([s1,s2,s3],axis=1))

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [156]:
# 데이터 그룹화
import numpy as np
from pandas import DataFrame

df= DataFrame({"key1":['a','a','b','b','a'],
             "key2":['one','two','one','two','one'],
              "data1":np.random.randn(5),
              "data2":np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  0.810404 -0.397278
1    a  two  0.895727  0.197480
2    b  one  1.251194  0.787766
3    b  two -0.072400  0.756538
4    a  one -3.094999  2.422080

In [157]:
g1 = df['data1'].groupby(df['key1'])
g1.mean()
# sql
# select avg(data1)
# from df
# group by key1

key1
a   -0.462956
b    0.589397
Name: data1, dtype: float64

In [158]:
g1 = df['data1'].groupby(df['key1']).mean()
g1

key1
a   -0.462956
b    0.589397
Name: data1, dtype: float64

In [159]:
# key2 값이 동일한 대상끼리 data2 의 평균
g2=df['data2'].groupby(df['key2']).mean()
g2

key2
one    0.937522
two    0.477009
Name: data2, dtype: float64

In [160]:
# key1,key2의 값이 동일한 대상끼리 data1 의 평균
g3=df['data1'].groupby([df['key1'],df['key2']]).mean()
g3

key1  key2
a     one    -1.142298
      two     0.895727
b     one     1.251194
      two    -0.072400
Name: data1, dtype: float64

In [161]:
# pivot table : 데이터 중에 두개를 키로 하여 테이블 작성
data = {
    "city":['서울','경기','서울','경기'],
    "year":[2000,2000,2010,2005],
    "pop":[1000,900,1005,1100]
}
data

{'city': ['서울', '경기', '서울', '경기'],
 'year': [2000, 2000, 2010, 2005],
 'pop': [1000, 900, 1005, 1100]}

In [162]:
df = DataFrame(data)
df

city  year   pop
0   서울  2000  1000
1   경기  2000   900
2   서울  2010  1005
3   경기  2005  1100

In [163]:
df.pivot('city','year','pop')

year    2000    2005    2010
city                        
경기     900.0  1100.0     NaN
서울    1000.0     NaN  1005.0

In [164]:
df.pivot('year','city','pop')

city      경기      서울
year                
2000   900.0  1000.0
2005  1100.0     NaN
2010     NaN  1005.0

In [165]:
# 인구 정보를 기술통계량 값 구하기
df['pop'].describe()

count       4.000000
mean     1001.250000
std        81.687922
min       900.000000
25%       975.000000
50%      1002.500000
75%      1028.750000
max      1100.000000
Name: pop, dtype: float64