In [6]:
# 8행 8열 짜리 ndarray 타입의 행렬 생성

# 0  0  0  0  0  0  0  0
# 0  15 15 15 15 15 15 0
# 0  15 0  0  0  0  15 0
# 0  15 0  0  0  0  15 0
# 0  15 0  0  0  0  15 0
# 0  15 0  0  0  0  15 0
# 0  15 15 15 15 15 15 0
# 0  0  0  0  0  0  0  0

import numpy as np
x = np.zeros((8,8))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
x[1:7,1:7] = 15
x[2:6,2:6] = 0
print(x)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 15. 15. 15. 15. 15. 15.  0.]
 [ 0. 15.  0.  0.  0.  0. 15.  0.]
 [ 0. 15.  0.  0.  0.  0. 15.  0.]
 [ 0. 15.  0.  0.  0.  0. 15.  0.]
 [ 0. 15.  0.  0.  0.  0. 15.  0.]
 [ 0. 15. 15. 15. 15. 15. 15.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [8]:
# 2행 2열 짜리 필터 행렬
k1 = np.zeros((2,2))
k1[0,0] = 1; k1[0,1] = 4;
k1[1,0] = 7; k1[1,1] = 3;
k1

array([[1., 4.],
       [7., 3.]])

In [9]:
# 2행 2열 짜리 필터 행렬
k2 = np.zeros((2,2))
k2[0,:] = 0.5;
k2[1,:] = -0.5;
k2

array([[ 0.5,  0.5],
       [-0.5, -0.5]])

In [16]:
from scipy.ndimage.filters import convolve
phi1 = convolve(x,k1)
phi1

array([[ 15.,  75.,  75.,  75.,  75.,  75.,  60.,   0.],
       [120., 210., 150., 150., 150., 165., 105.,   0.],
       [120., 105.,   0.,   0.,   0., 120., 105.,   0.],
       [120., 105.,   0.,   0.,   0., 120., 105.,   0.],
       [120., 105.,   0.,   0.,   0., 120., 105.,   0.],
       [120., 120.,  75.,  75.,  75., 180., 105.,   0.],
       [105., 150., 150., 150., 150., 150.,  45.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [13]:
# Pooling : 계산되는 부피를 줄이는 작업 
# max pooling : 대표되는 큰 값을 대표로 정함
# average pooling : 평균을 대표로 정함

In [14]:
from skimage.measure import block_reduce

In [17]:
phi1r = block_reduce(phi1, (2,2), np.max)
print(phi1r)

[[210. 150. 165. 105.]
 [120.   0. 120. 105.]
 [120.  75. 180. 105.]
 [150. 150. 150.  45.]]


In [18]:
# 두번째 필터로 적용
phi2 = convolve(x,k2)
phi2

array([[  7.5,  15. ,  15. ,  15. ,  15. ,  15. ,   7.5,   0. ],
       [  0. ,  -7.5, -15. , -15. , -15. ,  -7.5,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   7.5,  15. ,  15. ,  15. ,   7.5,   0. ,   0. ],
       [ -7.5, -15. , -15. , -15. , -15. , -15. ,  -7.5,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ]])

In [20]:
phi2r = block_reduce(phi2, (2,2), np.average)
print(phi2r)

[[ 3.75   0.     1.875  1.875]
 [ 0.     0.     0.     0.   ]
 [ 1.875  7.5    5.625  0.   ]
 [-5.625 -7.5   -7.5   -1.875]]
